language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_script:
  - npm install -g postcss-cli autoprefixer less bower
  - bower install

install:
  - pip install -q -r requirements/main.txt
  - pip install -q -r requirements/test.txt
  - pip install -q -e .

script:
  - py.test tests
